<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerVjV71GT\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerVjV71GT/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerVjV71GT.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerVjV71GT\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerVjV71GT\App_KernelDevDebugContainer([
    'container.build_hash' => 'VjV71GT',
    'container.build_id' => '01449dcf',
    'container.build_time' => 1613668598,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerVjV71GT');
