<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerMH16yid\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerMH16yid/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerMH16yid.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerMH16yid\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerMH16yid\App_KernelDevDebugContainer([
    'container.build_hash' => 'MH16yid',
    'container.build_id' => 'd956576f',
    'container.build_time' => 1613621571,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerMH16yid');
