<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerHsq23Xx\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerHsq23Xx/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerHsq23Xx.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerHsq23Xx\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerHsq23Xx\App_KernelDevDebugContainer([
    'container.build_hash' => 'Hsq23Xx',
    'container.build_id' => 'e4c0824b',
    'container.build_time' => 1613809533,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerHsq23Xx');
