<?php

namespace ContainerImxRzZh;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getArticle2Service extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'App\DataPersister\Article' shared autowired service.
     *
     * @return \App\DataPersister\Article
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/api-platform/core/src/DataPersister/DataPersisterInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/api-platform/core/src/DataPersister/ContextAwareDataPersisterInterface.php';
        include_once \dirname(__DIR__, 4).'/src/DataPersister/Article.php';
        include_once \dirname(__DIR__, 4).'/src/Factory/EmailInterface.php';
        include_once \dirname(__DIR__, 4).'/src/Factory/Email.php';

        return $container->privates['App\\DataPersister\\Article'] = new \App\DataPersister\Article(($container->privates['App\\DataPersister\\Article.inner'] ?? $container->load('getArticle_InnerService')), ($container->privates['mailer.mailer'] ?? $container->load('getMailer_MailerService')), ($container->privates['security.helper'] ?? $container->load('getSecurity_HelperService')), ($container->privates['App\\Factory\\Email'] ?? ($container->privates['App\\Factory\\Email'] = new \App\Factory\Email())));
    }
}
