<?php

namespace ContainerImxRzZh;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAuthentificationCheckerService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'App\Auth\AuthentificationChecker' shared autowired service.
     *
     * @return \App\Auth\AuthentificationChecker
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Auth/AuthentificationCheckerInterface.php';
        include_once \dirname(__DIR__, 4).'/src/Auth/AuthentificationChecker.php';

        return $container->privates['App\\Auth\\AuthentificationChecker'] = new \App\Auth\AuthentificationChecker(($container->privates['security.helper'] ?? $container->load('getSecurity_HelperService')));
    }
}
