<?php

namespace ContainerImxRzZh;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCurrentUserForArticlesSubscriberService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'App\Events\CurrentUserForArticlesSubscriber' shared autowired service.
     *
     * @return \App\Events\CurrentUserForArticlesSubscriber
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Events/CurrentUserForArticlesSubscriber.php';

        return $container->privates['App\\Events\\CurrentUserForArticlesSubscriber'] = new \App\Events\CurrentUserForArticlesSubscriber(($container->privates['security.helper'] ?? $container->load('getSecurity_HelperService')));
    }
}
