<?php

namespace ContainerImxRzZh;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEmailService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'App\Factory\Email' shared autowired service.
     *
     * @return \App\Factory\Email
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Factory/EmailInterface.php';
        include_once \dirname(__DIR__, 4).'/src/Factory/Email.php';

        return $container->privates['App\\Factory\\Email'] = new \App\Factory\Email();
    }
}
