<?php

namespace ContainerImxRzZh;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getGesdinet_Jwtrefreshtoken_UserProviderService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'gesdinet.jwtrefreshtoken.user_provider' shared service.
     *
     * @return \Gesdinet\JWTRefreshTokenBundle\Security\Provider\RefreshTokenProvider
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/security-core/User/UserProviderInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/gesdinet/jwt-refresh-token-bundle/Security/Provider/RefreshTokenProvider.php';

        return $container->privates['gesdinet.jwtrefreshtoken.user_provider'] = new \Gesdinet\JWTRefreshTokenBundle\Security\Provider\RefreshTokenProvider(($container->services['gesdinet.jwtrefreshtoken.refresh_token_manager'] ?? $container->load('getGesdinet_Jwtrefreshtoken_RefreshTokenManagerService')));
    }
}
