<?php

namespace ContainerImxRzZh;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getJsonResponseService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'App\Factory\JsonResponse' shared autowired service.
     *
     * @return \App\Factory\JsonResponse
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Factory/JsonResponseInterface.php';
        include_once \dirname(__DIR__, 4).'/src/Factory/JsonResponse.php';

        return $container->privates['App\\Factory\\JsonResponse'] = new \App\Factory\JsonResponse();
    }
}
