<?php

namespace ContainerImxRzZh;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMiniblog_Normalizer_ResourceAccessExceptionService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'miniblog.normalizer.resource_access_exception' shared autowired service.
     *
     * @return \App\Normalizer\ResourceAccessExceptionNormalizer
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Normalizer/NormalizerInterface.php';
        include_once \dirname(__DIR__, 4).'/src/Normalizer/AbstractNormaliser.php';
        include_once \dirname(__DIR__, 4).'/src/Normalizer/ResourceAccessExceptionNormalizer.php';
        include_once \dirname(__DIR__, 4).'/src/Services/ExceptionNormaliserFormatterInterface.php';
        include_once \dirname(__DIR__, 4).'/src/Services/ExceptionNormalizerFormatter.php';

        return $container->privates['miniblog.normalizer.resource_access_exception'] = new \App\Normalizer\ResourceAccessExceptionNormalizer(['type' => 'App\\Exceptions\\ResourceAccessException'], ($container->privates['App\\Services\\ExceptionNormalizerFormatter'] ?? ($container->privates['App\\Services\\ExceptionNormalizerFormatter'] = new \App\Services\ExceptionNormalizerFormatter())));
    }
}
