<?php

namespace ContainerImxRzZh;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getResourceAccessCheckerService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'App\Auth\ResourceAccessChecker' shared autowired service.
     *
     * @return \App\Auth\ResourceAccessChecker
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Auth/ResourceAccessCheckerInterface.php';
        include_once \dirname(__DIR__, 4).'/src/Auth/ResourceAccessChecker.php';

        return $container->privates['App\\Auth\\ResourceAccessChecker'] = new \App\Auth\ResourceAccessChecker(($container->privates['security.helper'] ?? $container->load('getSecurity_HelperService')));
    }
}
