<?php

namespace ContainerImxRzZh;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getResourceUpdaterSubscriberService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'App\Events\ResourceUpdaterSubscriber' shared autowired service.
     *
     * @return \App\Events\ResourceUpdaterSubscriber
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Events/ResourceUpdaterSubscriber.php';

        return $container->privates['App\\Events\\ResourceUpdaterSubscriber'] = new \App\Events\ResourceUpdaterSubscriber(($container->privates['App\\Services\\ResourceUpdater'] ?? $container->load('getResourceUpdaterService')));
    }
}
