<?php

namespace ContainerImxRzZh;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSecurity_Firewall_Map_Context_RefreshService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'security.firewall.map.context.refresh' shared service.
     *
     * @return \Symfony\Bundle\SecurityBundle\Security\FirewallContext
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/security-bundle/Security/FirewallContext.php';

        return $container->privates['security.firewall.map.context.refresh'] = new \Symfony\Bundle\SecurityBundle\Security\FirewallContext(new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['security.channel_listener'] ?? $container->load('getSecurity_ChannelListenerService'));
            yield 1 => ($container->privates['security.authentication.listener.anonymous.refresh'] ?? $container->load('getSecurity_Authentication_Listener_Anonymous_RefreshService'));
            yield 2 => ($container->privates['security.access_listener'] ?? $container->load('getSecurity_AccessListenerService'));
        }, 3), ($container->privates['security.exception_listener.refresh'] ?? $container->load('getSecurity_ExceptionListener_RefreshService')), NULL, ($container->privates['security.firewall.map.config.refresh'] ?? $container->load('getSecurity_Firewall_Map_Config_RefreshService')));
    }
}
