<?php

namespace ContainerFs7vz0n;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMiniblog_Events_ExceptionSubscriberService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'miniblog.events.exception_subscriber' shared autowired service.
     *
     * @return \App\Events\ExceptionSubscriber
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Events/ExceptionSubscriber.php';
        include_once \dirname(__DIR__, 4).'/src/Services/ExceptionNormaliserFormatterInterface.php';
        include_once \dirname(__DIR__, 4).'/src/Services/ExceptionNormalizerFormatter.php';
        include_once \dirname(__DIR__, 4).'/src/Factory/JsonResponseInterface.php';
        include_once \dirname(__DIR__, 4).'/src/Factory/JsonResponse.php';

        $container->privates['miniblog.events.exception_subscriber'] = $instance = new \App\Events\ExceptionSubscriber(($container->services['.container.private.serializer'] ?? $container->get_Container_Private_SerializerService()), ($container->privates['App\\Services\\ExceptionNormalizerFormatter'] ?? ($container->privates['App\\Services\\ExceptionNormalizerFormatter'] = new \App\Services\ExceptionNormalizerFormatter())), ($container->privates['App\\Factory\\JsonResponse'] ?? ($container->privates['App\\Factory\\JsonResponse'] = new \App\Factory\JsonResponse())));

        $instance->addNormalizer(($container->privates['miniblog.normalizer.resource_access_exception'] ?? $container->load('getMiniblog_Normalizer_ResourceAccessExceptionService')));
        $instance->addNormalizer(($container->privates['miniblog.normalizer.authentification_exception'] ?? $container->load('getMiniblog_Normalizer_AuthentificationExceptionService')));
        $instance->addNormalizer(($container->privates['miniblog.normalizer.authentification_not_found_exception'] ?? $container->load('getMiniblog_Normalizer_AuthentificationNotFoundExceptionService')));

        return $instance;
    }
}
