<?php

namespace ContainerFs7vz0n;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getResourceUpdaterService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'App\Services\ResourceUpdater' shared autowired service.
     *
     * @return \App\Services\ResourceUpdater
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Services/ResourceUpdaterInterface.php';
        include_once \dirname(__DIR__, 4).'/src/Services/ResourceUpdater.php';

        return $container->privates['App\\Services\\ResourceUpdater'] = new \App\Services\ResourceUpdater(($container->privates['App\\Auth\\ResourceAccessChecker'] ?? $container->load('getResourceAccessCheckerService')), ($container->privates['App\\Auth\\AuthentificationChecker'] ?? $container->load('getAuthentificationCheckerService')));
    }
}
