<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFs7vz0n\App_KernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFs7vz0n/App_KernelTestDebugContainer.php') {
    touch(__DIR__.'/ContainerFs7vz0n.legacy');

    return;
}

if (!\class_exists(App_KernelTestDebugContainer::class, false)) {
    \class_alias(\ContainerFs7vz0n\App_KernelTestDebugContainer::class, App_KernelTestDebugContainer::class, false);
}

return new \ContainerFs7vz0n\App_KernelTestDebugContainer([
    'container.build_hash' => 'Fs7vz0n',
    'container.build_id' => '21e6b908',
    'container.build_time' => 1613623221,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerFs7vz0n');
