<?php

namespace ContainerMH16yid;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMiniblog_Events_ExceptionSubscriberService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'miniblog.events.exception_subscriber' shared autowired service.
     *
     * @return \App\Events\ExceptionSubscriber
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Events/ExceptionSubscriber.php';
        include_once \dirname(__DIR__, 4).'/src/Normalizer/NormalizerInterface.php';
        include_once \dirname(__DIR__, 4).'/src/Normalizer/AbstractNormaliser.php';
        include_once \dirname(__DIR__, 4).'/src/Normalizer/ResourceAccessExceptionNormalizer.php';
        include_once \dirname(__DIR__, 4).'/src/Normalizer/AuthentificationExceptionNormalizer.php';
        include_once \dirname(__DIR__, 4).'/src/Normalizer/NotfoundExceptionNormalizer.php';
        include_once \dirname(__DIR__, 4).'/src/Services/ExceptionNormaliserFormatterInterface.php';
        include_once \dirname(__DIR__, 4).'/src/Services/ExceptionNormalizerFormatter.php';
        include_once \dirname(__DIR__, 4).'/src/Factory/JsonResponseInterface.php';
        include_once \dirname(__DIR__, 4).'/src/Factory/JsonResponse.php';

        $a = ($container->privates['App\\Services\\ExceptionNormalizerFormatter'] ?? ($container->privates['App\\Services\\ExceptionNormalizerFormatter'] = new \App\Services\ExceptionNormalizerFormatter()));

        $container->privates['miniblog.events.exception_subscriber'] = $instance = new \App\Events\ExceptionSubscriber(($container->services['.container.private.serializer'] ?? $container->get_Container_Private_SerializerService()), $a, ($container->privates['App\\Factory\\JsonResponse'] ?? ($container->privates['App\\Factory\\JsonResponse'] = new \App\Factory\JsonResponse())));

        $instance->addNormalizer(new \App\Normalizer\ResourceAccessExceptionNormalizer(['type' => 'App\\Exceptions\\ResourceAccessException'], $a));
        $instance->addNormalizer(new \App\Normalizer\AuthentificationExceptionNormalizer(['type' => 'App\\Exceptions\\AuthentificationException'], $a));
        $instance->addNormalizer(new \App\Normalizer\NotfoundExceptionNormalizer(['type' => 'Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException'], $a));

        return $instance;
    }
}
