<?php

namespace ContainerMH16yid;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMiniblogApi_Event_JwtCreatedListenerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'miniblog_api.event.jwt_created_listener' shared autowired service.
     *
     * @return \App\EventListener\JWTCreatedListener
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/EventListener/JWTCreatedListener.php';

        return $container->privates['miniblog_api.event.jwt_created_listener'] = new \App\EventListener\JWTCreatedListener(($container->privates['security.helper'] ?? $container->load('getSecurity_HelperService')));
    }
}
