<?php

namespace ContainerMH16yid;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getResourceUpdaterSubscriberService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Events\ResourceUpdaterSubscriber' shared autowired service.
     *
     * @return \App\Events\ResourceUpdaterSubscriber
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Events/ResourceUpdaterSubscriber.php';
        include_once \dirname(__DIR__, 4).'/src/Services/ResourceUpdaterInterface.php';
        include_once \dirname(__DIR__, 4).'/src/Services/ResourceUpdater.php';
        include_once \dirname(__DIR__, 4).'/src/Auth/ResourceAccessCheckerInterface.php';
        include_once \dirname(__DIR__, 4).'/src/Auth/ResourceAccessChecker.php';
        include_once \dirname(__DIR__, 4).'/src/Auth/AuthentificationCheckerInterface.php';
        include_once \dirname(__DIR__, 4).'/src/Auth/AuthentificationChecker.php';

        $a = ($container->privates['security.helper'] ?? $container->load('getSecurity_HelperService'));

        return $container->privates['App\\Events\\ResourceUpdaterSubscriber'] = new \App\Events\ResourceUpdaterSubscriber(new \App\Services\ResourceUpdater(new \App\Auth\ResourceAccessChecker($a), new \App\Auth\AuthentificationChecker($a)));
    }
}
