<?php

namespace ContainerVjV71GT;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Security_RequestMatcher_KRuynPjService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.security.request_matcher.KRuynPj' shared service.
     *
     * @return \Symfony\Component\HttpFoundation\RequestMatcher
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/http-foundation/RequestMatcherInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/http-foundation/RequestMatcher.php';

        return $container->privates['.security.request_matcher.KRuynPj'] = new \Symfony\Component\HttpFoundation\RequestMatcher('^/api/articles', NULL, [0 => 'POST', 1 => 'PUT', 2 => 'PATCH', 3 => 'DELETE']);
    }
}
