<?php

namespace ContainerNOxPxEr;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getArticleUpdatedAtService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\ArticleUpdatedAt' shared autowired service.
     *
     * @return \App\Controller\ArticleUpdatedAt
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Controller/ArticleUpdatedAt.php';

        return $container->services['App\\Controller\\ArticleUpdatedAt'] = new \App\Controller\ArticleUpdatedAt();
    }
}
