<?php

namespace ContainerYTIZm4C;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_GBedJQMService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.gBedJQM' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.gBedJQM'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'data' => ['privates', '.errored..service_locator.gBedJQM.App\\Entity\\Article', NULL, 'Cannot autowire service ".service_locator.gBedJQM": it references class "App\\Entity\\Article" but no such service exists.'],
        ], [
            'data' => 'App\\Entity\\Article',
        ]);
    }
}
